Repository sonata-project/SonataArticleBundle, pull requests merged in 2019-01, with the labels that each got.

#108 Remove useless backslash
  src/DependencyInjection/Configuration.php
Labels: critical, pedantic

#111 [Docs] big cleanup
  docs/reference/configuration.rst
  docs/reference/custom_fragment.rst
  docs/reference/getting_started.rst
  docs/reference/installation.rst
Labels: docs

#110 Fix Article and Fragment interfaces return types
  src/Model/AbstractArticle.php
  src/Model/AbstractFragment.php
  src/Model/ArticleFragmentInterface.php
  src/Model/ArticleInterface.php
  src/Model/FragmentInterface.php
Labels: minor
